# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f84a76beaed64f87c29e71b454d92c60cf57d9ca7df05c240b51ad486264e949309d390b4a2eb4c74541027e4e7074dfcf767e69cb3bd5276c0c187b239d9ba

test:
  secret_key_base: eb78169de9befa785a369eb655cfa92c7ad879e93033db4fdae51665f99b70962efacd0f096ad1a25b91615cf414311ce2bb1b0c5db7864cfb6dec59ce9a73a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
